const TYPES = {
  CLIENT: Symbol("CLIENT"),
  REST: Symbol("REST"),
  DATABASE: Symbol("DATABASE"),
  LOGGER: Symbol("LOGGER"),
  BROWSER: Symbol("BROWSER"),
  DISCORD_HANDLER: Symbol("DISCORD_HANDLER"),
  COMMAND: Symbol("COMMAND"),
  INTERACTION: Symbol("INTERACTION"),
  YT_HTTP: Symbol("YT_HTTP"),
  JAIL_REPO: Symbol("JAIL_REPO"),
  JAIL_MANAGER: Symbol("JAIL_MANAGER"),
  JAIL_STATE: Symbol("JAIL_STATE"),
  REMINDER_REPO: Symbol("REMINDER_REPO"),
  REMINDER_SCHEDULER: Symbol("REMINDER_SCHEDULER"),
  WATCHER_REPO: Symbol("WATCHER_REPO"),
  WATCHER_SCHEDULER: Symbol("WATCHER_SCHEDULER"),
  WATCHER_PIPELINE: Symbol("WATCHER_PIPELINE"),
  WATCHER_PIPELINE_CONTEXT: Symbol("WATCHER_PIPELINE_CONTEXT"),
}

export { TYPES }
